# Generated by Django 5.2.7 on 2025-10-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del videojuego', max_length=100)),
                ('desarrollador', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('plataforma', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='portadas_videojuegos/')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videojuegos', to='app_videojuegos_proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
            },
        ),
    ]
